import { Task } from "@/lib/schemas/task";

export const tasks: Task[] = [
    {
        id: 1,
        titulo: "Tarea 1",
        prioridad: "alta",
        tipo: "quimico",
        empleado_id: 1001,
        creador_id: 2001,
        fecha_creacion: "2023-10-25",
        fecha_limite: "2023-11-10",
        evidencia: "",
        estado: "sin_iniciar",
    },
    {
        id: 2,
        titulo: "Tarea 2",
        prioridad: "media",
        tipo: "agua",
        empleado_id: 1002,
        creador_id: 2002,
        fecha_creacion: "2023-10-26",
        fecha_limite: "2023-11-15",
        evidencia: "",
        estado: "en_proceso",
    },
    {
        id: 3,
        titulo: "Tarea 3",
        prioridad: "baja",
        tipo: "reciclaje",
        empleado_id: 1003,
        creador_id: 2003,
        fecha_creacion: "2023-10-27",
        fecha_limite: "2023-11-20",
        evidencia: "",
        estado: "ejecutada",
    },
    {
        id: 4,
        titulo: "Tarea 4",
        prioridad: "alta",
        tipo: "quimico",
        empleado_id: 1004,
        creador_id: 2004,
        fecha_creacion: "2023-10-28",
        fecha_limite: "2023-11-25",
        evidencia: "",
        estado: "sin_iniciar",
    },
    {
        id: 5,
        titulo: "Tarea 5",
        prioridad: "media",
        tipo: "agua",
        empleado_id: 1005,
        creador_id: 2005,
        fecha_creacion: "2023-10-29",
        fecha_limite: "2023-11-30",
        evidencia: "",
        estado: "en_proceso",
    },
    {
        id: 6,
        titulo: "Tarea 6",
        prioridad: "baja",
        tipo: "reciclaje",
        empleado_id: 1006,
        creador_id: 2006,
        fecha_creacion: "2023-10-30",
        fecha_limite: "2023-12-05",
        evidencia: "",
        estado: "ejecutada",
    },
    {
        id: 7,
        titulo: "Tarea 7",
        prioridad: "alta",
        tipo: "quimico",
        empleado_id: 1007,
        creador_id: 2007,
        fecha_creacion: "2023-11-01",
        fecha_limite: "2023-12-10",
        evidencia: "",
        estado: "sin_iniciar",
    },
    {
        id: 8,
        titulo: "Tarea 8",
        prioridad: "media",
        tipo: "agua",
        empleado_id: 1008,
        creador_id: 2008,
        fecha_creacion: "2023-11-02",
        fecha_limite: "2023-12-15",
        evidencia: "",
        estado: "en_proceso",
    },
    {
        id: 9,
        titulo: "Tarea 9",
        prioridad: "baja",
        tipo: "reciclaje",
        empleado_id: 1009,
        creador_id: 2009,
        fecha_creacion: "2023-11-03",
        fecha_limite: "2023-12-20",
        evidencia: "",
        estado: "ejecutada",
    },
    {
        id: 10,
        titulo: "Tarea 10",
        prioridad: "alta",
        tipo: "quimico",
        empleado_id: 1010,
        creador_id: 2010,
        fecha_creacion: "2023-11-04",
        fecha_limite: "2023-12-25",
        evidencia: "",
        estado: "sin_iniciar",
    },
    {
        id: 11,
        titulo: "Tarea 11",
        prioridad: "media",
        tipo: "agua",
        empleado_id: 1011,
        creador_id: 2011,
        fecha_creacion: "2023-11-05",
        fecha_limite: "2023-12-30",
        evidencia: "",
        estado: "en_proceso",
    },
    {
        id: 12,
        titulo: "Tarea 12",
        prioridad: "baja",
        tipo: "reciclaje",
        empleado_id: 1012,
        creador_id: 2012,
        fecha_creacion: "2023-11-06",
        fecha_limite: "2024-01-05",
        evidencia: "",
        estado: "ejecutada",
    },
    {
        id: 13,
        titulo: "Tarea 13",
        prioridad: "alta",
        tipo: "quimico",
        empleado_id: 1013,
        creador_id: 2013,
        fecha_creacion: "2023-11-07",
        fecha_limite: "2024-01-10",
        evidencia: "",
        estado: "sin_iniciar",
    },
    {
        id: 14,
        titulo: "Tarea 14",
        prioridad: "media",
        tipo: "agua",
        empleado_id: 1014,
        creador_id: 2014,
        fecha_creacion: "2023-11-08",
        fecha_limite: "2024-01-15",
        evidencia: "",
        estado: "en_proceso",
    },
    {
        id: 15,
        titulo: "Tarea 15",
        prioridad: "baja",
        tipo: "reciclaje",
        empleado_id: 1015,
        creador_id: 2015,
        fecha_creacion: "2023-11-09",
        fecha_limite: "2024-01-15",
        evidencia: "",
        estado: "en_proceso",
    },
];
